// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsBdGOHdQFkR63TkbppwIuLggdz6VDmjE',
    appId: '1:881824533107:web:17caf3ba7ce67e2668f806',
    messagingSenderId: '881824533107',
    projectId: 'yarn-ea60d',
    authDomain: 'yarn-ea60d.firebaseapp.com',
    storageBucket: 'yarn-ea60d.firebasestorage.app',
    measurementId: 'G-11V67W3THK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7cS8O41x2YRMxgiXvT6_AcG_YL0rNrmY',
    appId: '1:881824533107:android:54c4dc7f161d0cf168f806',
    messagingSenderId: '881824533107',
    projectId: 'yarn-ea60d',
    storageBucket: 'yarn-ea60d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhUsYDjNXNkEUo_nRjJqlHL-OTGvkrYE',
    appId: '1:881824533107:ios:ca289f31953a37a468f806',
    messagingSenderId: '881824533107',
    projectId: 'yarn-ea60d',
    storageBucket: 'yarn-ea60d.firebasestorage.app',
    iosBundleId: 'com.yarn.yarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVhUsYDjNXNkEUo_nRjJqlHL-OTGvkrYE',
    appId: '1:881824533107:ios:ca289f31953a37a468f806',
    messagingSenderId: '881824533107',
    projectId: 'yarn-ea60d',
    storageBucket: 'yarn-ea60d.firebasestorage.app',
    iosBundleId: 'com.yarn.yarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsBdGOHdQFkR63TkbppwIuLggdz6VDmjE',
    appId: '1:881824533107:web:aae582352aaa046568f806',
    messagingSenderId: '881824533107',
    projectId: 'yarn-ea60d',
    authDomain: 'yarn-ea60d.firebaseapp.com',
    storageBucket: 'yarn-ea60d.firebasestorage.app',
    measurementId: 'G-9N99BX3B39',
  );
}
