// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvdeItMLSbO1N3adrP6tB9TdbmcOE7dU',
    appId: '1:276804162614:web:c31f4a33f06a911e737497',
    messagingSenderId: '276804162614',
    projectId: 'yarn-e4ebb',
    authDomain: 'yarn-e4ebb.firebaseapp.com',
    storageBucket: 'yarn-e4ebb.firebasestorage.app',
    measurementId: 'G-4ME6E1ZVL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLO9OuTtkcGMzyLkIwJ_Ps9dR4RK0eEE',
    appId: '1:276804162614:android:92a04713e3055b73737497',
    messagingSenderId: '276804162614',
    projectId: 'yarn-e4ebb',
    storageBucket: 'yarn-e4ebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD1j-eY6IgVXGNyE9_MIOQIrakOBf02Z8',
    appId: '1:276804162614:ios:020b8ab9026c9e9a737497',
    messagingSenderId: '276804162614',
    projectId: 'yarn-e4ebb',
    storageBucket: 'yarn-e4ebb.firebasestorage.app',
    iosBundleId: 'com.yarn.yarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD1j-eY6IgVXGNyE9_MIOQIrakOBf02Z8',
    appId: '1:276804162614:ios:020b8ab9026c9e9a737497',
    messagingSenderId: '276804162614',
    projectId: 'yarn-e4ebb',
    storageBucket: 'yarn-e4ebb.firebasestorage.app',
    iosBundleId: 'com.yarn.yarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKvdeItMLSbO1N3adrP6tB9TdbmcOE7dU',
    appId: '1:276804162614:web:483fc770fe876554737497',
    messagingSenderId: '276804162614',
    projectId: 'yarn-e4ebb',
    authDomain: 'yarn-e4ebb.firebaseapp.com',
    storageBucket: 'yarn-e4ebb.firebasestorage.app',
    measurementId: 'G-1HPZV72KK2',
  );

}